version: "3.8"
services:
  centos:
    build: ./docker
    ports: 
      - 8080:80
    volumes:
        - ./src:/var/www/html
    working_dir: /var/www/html
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined